// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libsceaudioin.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::AudioIn{

int PS4_SYSV_ABI sceAudioInChangeAppModuleState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInCountPorts()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInDeviceHqOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInDeviceIdHqOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInDeviceIdOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInDeviceOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInDeviceOpenEx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInExtClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInExtCtrl()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInExtInput()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInExtOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInExtSetAecMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInGetGain()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInGetHandleStatusInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInGetRerouteCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInGetSilentState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInHqOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInHqOpenEx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInInput()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInInputs()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInIsSharedDevice()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInOpenEx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetAllMute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetCompressorPreGain()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetConnections()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetConnectionsForUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetDevConnection()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetFocusForUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetMode2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetPortConnections()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetPortStatuses()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetSparkParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetSparkSideTone()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetUsbGain()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInSetUserMute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInVmicCreate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInVmicDestroy()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioInVmicWrite()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceAudioIn(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("IQtWgnrw6v8", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInChangeAppModuleState );
 LIB_FUNCTION("Jh6WbHhnI68", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInClose );
 LIB_FUNCTION("8mtcsG-Qp5E", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInCountPorts );
 LIB_FUNCTION("5qRVfxOmbno", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInDeviceHqOpen );
 LIB_FUNCTION("gUNabrUkZNg", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInDeviceIdHqOpen );
 LIB_FUNCTION("X-AQLtdxQOo", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInDeviceIdOpen );
 LIB_FUNCTION("VoX9InuwwTg", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInDeviceOpen );
 LIB_FUNCTION("48-miagyJ2I", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInDeviceOpenEx );
 LIB_FUNCTION("kFKJ3MVcDuo", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInExtClose );
 LIB_FUNCTION("mhAfefP9m2g", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInExtCtrl );
 LIB_FUNCTION("KpBKoHKVKEc", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInExtInput );
 LIB_FUNCTION("YZ+3seW7CyY", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInExtOpen );
 LIB_FUNCTION("FVGWf8JaHOE", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInExtSetAecMode );
 LIB_FUNCTION("S-rDUfQk9sg", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInGetGain );
 LIB_FUNCTION("NJam1-F7lNY", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInGetHandleStatusInfo );
 LIB_FUNCTION("3shKmTrTw6c", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInGetRerouteCount );
 LIB_FUNCTION("BohEAQ7DlUE", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInGetSilentState );
 LIB_FUNCTION("nya-R5gDYhM", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInHqOpen );
 LIB_FUNCTION("CTh72m+IYbU", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInHqOpenEx );
 LIB_FUNCTION("SxQprgjttKE", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInInit );
 LIB_FUNCTION("LozEOU8+anM", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInInput );
 LIB_FUNCTION("rmgXsZ-2Tyk", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInInputs );
 LIB_FUNCTION("6QP1MzdFWhs", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInIsSharedDevice );
 LIB_FUNCTION("5NE8Sjc7VC8", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInOpen );
 LIB_FUNCTION("+DY07NwJb0s", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInOpenEx );
 LIB_FUNCTION("vYFsze1SqU8", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetAllMute );
 LIB_FUNCTION("vyh-T6sMqnw", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetCompressorPreGain );
 LIB_FUNCTION("YeBSNVAELe4", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetConnections );
 LIB_FUNCTION("thLNHvkWSeg", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetConnectionsForUser );
 LIB_FUNCTION("rcgv2ciDrtc", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetDevConnection );
 LIB_FUNCTION("iN3KqF-8R-w", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetFocusForUser );
 LIB_FUNCTION("VAzfxqDwbQ0", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetMode );
 LIB_FUNCTION("CwBFvAlOv7k", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetMode2 );
 LIB_FUNCTION("tQpOPpYwv7o", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetPortConnections );
 LIB_FUNCTION("NUWqWguYcNQ", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetPortStatuses );
 LIB_FUNCTION("U0ivfdKFZbA", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetSparkParam );
 LIB_FUNCTION("hWMCAPpqzDo", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetSparkSideTone );
 LIB_FUNCTION("nqXpw3MaN50", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetUsbGain );
 LIB_FUNCTION("arJp991xk5k", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInSetUserMute );
 LIB_FUNCTION("DVTn+iMSpBM", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInVmicCreate );
 LIB_FUNCTION("3ULZGIl+Acc", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInVmicDestroy );
 LIB_FUNCTION("4kHw99LUG3A", "libSceAudioIn" , 1 , "libSceAudioIn", 1, 1 , sceAudioInVmicWrite );
};

}