// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscenetctl.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::NetCtl{

int PS4_SYSV_ABI sceNetBweCheckCallbackIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweClearEventIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweFinishInternetConnectionTestIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweGetInfoIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweRegisterCallbackIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweSetInternetConnectionTestResultIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweStartInternetConnectionTestBandwidthTestIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweStartInternetConnectionTestIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetBweUnregisterCallbackIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetInfoV6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetResultV6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetStateV6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallbackV6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallbackV6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlCheckCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlCheckCallbackForLibIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlClearEventForLibIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlClearEventIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlConnectConfIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlConnectIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlConnectWithRetryIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlDisableBandwidthManagementIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlDisconnectIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlEnableBandwidthManagementIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetBandwidthInfoIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetEtherLinkMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetIfStat()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetInfoIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetInfoV6IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetNatInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetNatInfoIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetNetEvConfigInfoIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetResult()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetResultIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetResultV6IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetScanInfoBssidForSsidListScanIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetScanInfoBssidIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetScanInfoByBssidIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetScanInfoForSsidListScanIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetScanInfoForSsidScanIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetState2IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetStateIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetStateV6IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlGetWifiType()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlIsBandwidthManagementEnabledIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallbackForLibIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallbackIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallbackV6IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlScanIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlSetErrorNotificationEnabledIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlSetStunWithPaddingFlagIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlTerm()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallbackForLibIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallbackIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallbackV6IpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnsetStunWithPaddingFlagIpcInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_D8DCB6973537A3DC()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlCheckCallbackForNpToolkit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlClearEventForNpToolkit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlRegisterCallbackForNpToolkit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlUnregisterCallbackForNpToolkit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApCheckCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApClearEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApGetConnectInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApGetInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApGetResult()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApGetState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRegisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApStop()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApTerm()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApUnregisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApAppInitWpaKey()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApAppInitWpaKeyForQa()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApAppStartWithRetry()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApAppStartWithRetryPid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRestart()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpCheckCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpClearEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpGetInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpGetResult()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpGetState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpRegisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpStart()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpStartConf()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpStartWithRetry()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpStop()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNetCtlApRpUnregisterCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceNetCtl(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("XtClSOC1xcU", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweCheckCallbackIpcInt );
 LIB_FUNCTION("YALqoY4aeY0", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweClearEventIpcInt );
 LIB_FUNCTION("ouyROWhGUbM", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweFinishInternetConnectionTestIpcInt );
 LIB_FUNCTION("G4vltQ0Vs+0", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweGetInfoIpcInt );
 LIB_FUNCTION("GqETL5+INhU", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweRegisterCallbackIpcInt );
 LIB_FUNCTION("mEUt-phGd5E", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweSetInternetConnectionTestResultIpcInt );
 LIB_FUNCTION("pQLJV5SEAqk", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweStartInternetConnectionTestBandwidthTestIpcInt );
 LIB_FUNCTION("c+aYh130SV0", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweStartInternetConnectionTestIpcInt );
 LIB_FUNCTION("0lViPaTB-R8", "libSceNetBwe" , 1 , "libSceNetCtl", 1, 1 , sceNetBweUnregisterCallbackIpcInt );
 LIB_FUNCTION("Jy1EO5GdlcM", "libSceNetCtlV6" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetInfoV6 );
 LIB_FUNCTION("H5yARg37U5g", "libSceNetCtlV6" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetResultV6 );
 LIB_FUNCTION("+lxqIKeU9UY", "libSceNetCtlV6" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetStateV6 );
 LIB_FUNCTION("1NE9OWdBIww", "libSceNetCtlV6" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackV6 );
 LIB_FUNCTION("hIUVeUNxAwc", "libSceNetCtlV6" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackV6 );
 LIB_FUNCTION("iQw3iQPhvUQ", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlCheckCallback );
 LIB_FUNCTION("UF6H6+kjyQs", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlCheckCallbackForLibIpcInt );
 LIB_FUNCTION("vv6g8zoanL4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlClearEventForLibIpcInt );
 LIB_FUNCTION("8OJ86vFucfo", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlClearEventIpcInt );
 LIB_FUNCTION("HCD46HVTyQg", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlConnectConfIpcInt );
 LIB_FUNCTION("ID+Gq3Ddzbg", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlConnectIpcInt );
 LIB_FUNCTION("aPpic8K75YA", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlConnectWithRetryIpcInt );
 LIB_FUNCTION("9y4IcsJdTCc", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlDisableBandwidthManagementIpcInt );
 LIB_FUNCTION("qOefcpoSs0k", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlDisconnectIpcInt );
 LIB_FUNCTION("x9bSmRSE+hc", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlEnableBandwidthManagementIpcInt );
 LIB_FUNCTION("eCUIlA2t5CE", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetBandwidthInfoIpcInt );
 LIB_FUNCTION("2EfjPXVPk3s", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetEtherLinkMode );
 LIB_FUNCTION("teuK4QnJTGg", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetIfStat );
 LIB_FUNCTION("obuxdTiwkF8", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetInfo );
 LIB_FUNCTION("xstcTqAhTys", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetInfoIpcInt );
 LIB_FUNCTION("Jy1EO5GdlcM", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetInfoV6 );
 LIB_FUNCTION("arAQRFlwqaA", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetInfoV6IpcInt );
 LIB_FUNCTION("JO4yuTuMoKI", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetNatInfo );
 LIB_FUNCTION("x+cnsAxKSHo", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetNatInfoIpcInt );
 LIB_FUNCTION("hhTsdv99azU", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetNetEvConfigInfoIpcInt );
 LIB_FUNCTION("0cBgduPRR+M", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetResult );
 LIB_FUNCTION("NEtnusbZyAs", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetResultIpcInt );
 LIB_FUNCTION("H5yARg37U5g", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetResultV6 );
 LIB_FUNCTION("vdsTa93atXY", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetResultV6IpcInt );
 LIB_FUNCTION("wP0Ab2maR1Y", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetScanInfoBssidForSsidListScanIpcInt );
 LIB_FUNCTION("Wn-+887Lt2s", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetScanInfoBssidIpcInt );
 LIB_FUNCTION("FEdkOG1VbQo", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetScanInfoByBssidIpcInt );
 LIB_FUNCTION("irV8voIAHDw", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetScanInfoForSsidListScanIpcInt );
 LIB_FUNCTION("L97eAHI0xxs", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetScanInfoForSsidScanIpcInt );
 LIB_FUNCTION("uBPlr0lbuiI", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetState );
 LIB_FUNCTION("JXlI9EZVjf4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetState2IpcInt );
 LIB_FUNCTION("gvnJPMkSoAY", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetStateIpcInt );
 LIB_FUNCTION("+lxqIKeU9UY", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetStateV6 );
 LIB_FUNCTION("O8Fk4w5MWss", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetStateV6IpcInt );
 LIB_FUNCTION("BXW9b3R1Nw4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlGetWifiType );
 LIB_FUNCTION("gky0+oaNM4k", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlInit );
 LIB_FUNCTION("YtAnCkTR0K4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlIsBandwidthManagementEnabledIpcInt );
 LIB_FUNCTION("UJ+Z7Q+4ck0", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallback );
 LIB_FUNCTION("WRvDk2syatE", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackForLibIpcInt );
 LIB_FUNCTION("rqkh2kXvLSw", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackIpcInt );
 LIB_FUNCTION("1NE9OWdBIww", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackV6 );
 LIB_FUNCTION("ipqlpcIqRsQ", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackV6IpcInt );
 LIB_FUNCTION("reIsHryCDx4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlScanIpcInt );
 LIB_FUNCTION("LJYiiIS4HB0", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlSetErrorNotificationEnabledIpcInt );
 LIB_FUNCTION("DjuqqqV08Nk", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlSetStunWithPaddingFlagIpcInt );
 LIB_FUNCTION("Z4wwCFiBELQ", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlTerm );
 LIB_FUNCTION("Rqm2OnZMCz0", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallback );
 LIB_FUNCTION("urWaUWkEGZg", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackForLibIpcInt );
 LIB_FUNCTION("by9cbB7JGJE", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackIpcInt );
 LIB_FUNCTION("hIUVeUNxAwc", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackV6 );
 LIB_FUNCTION("Hjxpy28aID8", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackV6IpcInt );
 LIB_FUNCTION("1HSvkN9oxO4", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnsetStunWithPaddingFlagIpcInt );
 LIB_FUNCTION("2Ny2lzU3o9w", "libSceNetCtl" , 1 , "libSceNetCtl", 1, 1 , Func_D8DCB6973537A3DC );
 LIB_FUNCTION("u5oqtlIP+Fw", "libSceNetCtlForNpToolkit" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlCheckCallbackForNpToolkit );
 LIB_FUNCTION("saYB0b2ZWtI", "libSceNetCtlForNpToolkit" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlClearEventForNpToolkit );
 LIB_FUNCTION("wIsKy+TfeLs", "libSceNetCtlForNpToolkit" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlRegisterCallbackForNpToolkit );
 LIB_FUNCTION("2oUqKR5odGc", "libSceNetCtlForNpToolkit" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlUnregisterCallbackForNpToolkit );
 LIB_FUNCTION("19Ec7WkMFfQ", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApCheckCallback );
 LIB_FUNCTION("meFMaDpdsVI", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApClearEvent );
 LIB_FUNCTION("hfkLVdXmfnU", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApGetConnectInfo );
 LIB_FUNCTION("LXADzTIzM9I", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApGetInfo );
 LIB_FUNCTION("4jkLJc954+Q", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApGetResult );
 LIB_FUNCTION("AKZOzsb9whc", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApGetState );
 LIB_FUNCTION("FdN+edNRtiw", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApInit );
 LIB_FUNCTION("pmjobSVHuY0", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRegisterCallback );
 LIB_FUNCTION("r-pOyN6AhsM", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApStop );
 LIB_FUNCTION("cv5Y2efOTeg", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApTerm );
 LIB_FUNCTION("NpTcFtaQ-0E", "libSceNetCtlAp" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApUnregisterCallback );
 LIB_FUNCTION("R-4a9Yh4tG8", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApAppInitWpaKey );
 LIB_FUNCTION("5oLJoOVBbGU", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApAppInitWpaKeyForQa );
 LIB_FUNCTION("YtTwZ3pa4aQ", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApAppStartWithRetry );
 LIB_FUNCTION("sgWeDrEt24U", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApAppStartWithRetryPid );
 LIB_FUNCTION("amqSGH8l--s", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRestart );
 LIB_FUNCTION("DufQZgH5ISc", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpCheckCallback );
 LIB_FUNCTION("qhZbOi+2qLY", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpClearEvent );
 LIB_FUNCTION("VQl16Q+qXeY", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpGetInfo );
 LIB_FUNCTION("3pxwYqHzGcw", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpGetResult );
 LIB_FUNCTION("LEn8FGztKWc", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpGetState );
 LIB_FUNCTION("ofGsK+xoAaM", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpRegisterCallback );
 LIB_FUNCTION("mjFgpqNavHg", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpStart );
 LIB_FUNCTION("HMvaHoZWsn8", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpStartConf );
 LIB_FUNCTION("9Dxg7XSlr2s", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpStartWithRetry );
 LIB_FUNCTION("6uvAl4RlEyk", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpStop );
 LIB_FUNCTION("8eyH37Ns8tk", "libSceNetCtlApIpcInt" , 1 , "libSceNetCtl", 1, 1 , sceNetCtlApRpUnregisterCallback );
};

}