// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscenptrophy.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::NpTrophy{

int PS4_SYSV_ABI sceNpTrophyAbortHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyCaptureScreenshot()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophyDetails()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophyFlagArray()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophyGroupArray()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophyGroupDetails()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophySetInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophySetInfoInGroup()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophySetVersion()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigGetTrophyTitleDetails()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyConfigHasGroupFeature()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyCreateContext()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyCreateHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyDestroyContext()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyDestroyHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetGameIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetGameInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetGroupIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetGroupInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetTrophyIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetTrophyInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGetTrophyUnlockState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyGroupArrayGetNum()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntAbortHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntCheckNetSyncTitles()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntCreateHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntDestroyHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntGetLocalTrophySummary()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntGetProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntGetRunningTitle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntGetRunningTitles()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntGetTrpIconByUri()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntNetSyncTitle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyIntNetSyncTitles()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyNumInfoGetTotal()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyRegisterContext()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySetInfoGetTrophyFlagArray()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySetInfoGetTrophyNum()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyShowTrophyList()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemAbortHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemBuildGroupIconUri()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemBuildNetTrophyIconUri()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemBuildTitleIconUri()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemBuildTrophyIconUri()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemCheckNetSyncTitles()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemCheckRecoveryRequired()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemCloseStorage()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemCreateContext()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemCreateHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDbgCtl()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDebugLockTrophy()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDebugUnlockTrophy()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDestroyContext()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDestroyHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemDestroyTrophyConfig()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetDbgParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetDbgParamInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetGroupIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetLocalTrophySummary()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetNextTitleFileEntryStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTitleFileStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTitleIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTitleSyncStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyConfig()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyGroupData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyTitleData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetTrophyTitleIds()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetUserFileInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemGetUserFileStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemIsServerAvailable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemNetSyncTitle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemNetSyncTitles()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemOpenStorage()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemPerformRecovery()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemRemoveAll()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemRemoveTitleData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemRemoveUserData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemSetDbgParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophySystemSetDbgParamInt()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpTrophyUnlockTrophy()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_149656DA81D41C59()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_9F80071876FFA5F6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_F8EF6F5350A91990()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_FA7A2DD770447552()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceNpTrophy(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("aTnHs7W-9Uk", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyAbortHandle );
 LIB_FUNCTION("cqGkYAN-gRw", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyCaptureScreenshot );
 LIB_FUNCTION("lhE4XS9OJXs", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophyDetails );
 LIB_FUNCTION("qJ3IvrOoXg0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophyFlagArray );
 LIB_FUNCTION("zDjF2G+6tI0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophyGroupArray );
 LIB_FUNCTION("7Kh86vJqtxw", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophyGroupDetails );
 LIB_FUNCTION("ndLeNWExeZE", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophySetInfo );
 LIB_FUNCTION("6EOfS5SDgoo", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophySetInfoInGroup );
 LIB_FUNCTION("MW5ygoZqEBs", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophySetVersion );
 LIB_FUNCTION("3tWKpNKn5+I", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigGetTrophyTitleDetails );
 LIB_FUNCTION("iqYfxC12sak", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyConfigHasGroupFeature );
 LIB_FUNCTION("XbkjbobZlCY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyCreateContext );
 LIB_FUNCTION("q7U6tEAQf7c", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyCreateHandle );
 LIB_FUNCTION("E1Wrwd07Lr8", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyDestroyContext );
 LIB_FUNCTION("GNcF4oidY0Y", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyDestroyHandle );
 LIB_FUNCTION("HLwz1fRIycA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetGameIcon );
 LIB_FUNCTION("YYP3f2W09og", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetGameInfo );
 LIB_FUNCTION("w4uMPmErD4I", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetGroupIcon );
 LIB_FUNCTION("wTUwGfspKic", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetGroupInfo );
 LIB_FUNCTION("eBL+l6HG9xk", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetTrophyIcon );
 LIB_FUNCTION("qqUVGDgQBm0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetTrophyInfo );
 LIB_FUNCTION("LHuSmO3SLd8", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGetTrophyUnlockState );
 LIB_FUNCTION("Ht6MNTl-je4", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyGroupArrayGetNum );
 LIB_FUNCTION("u9plkqa2e0k", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntAbortHandle );
 LIB_FUNCTION("pE5yhroy9m0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntCheckNetSyncTitles );
 LIB_FUNCTION("edPIOFpEAvU", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntCreateHandle );
 LIB_FUNCTION("DSh3EXpqAQ4", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntDestroyHandle );
 LIB_FUNCTION("sng98qULzPA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntGetLocalTrophySummary );
 LIB_FUNCTION("t3CQzag7-zs", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntGetProgress );
 LIB_FUNCTION("jF-mCgGuvbQ", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntGetRunningTitle );
 LIB_FUNCTION("PeAyBjC5kp8", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntGetRunningTitles );
 LIB_FUNCTION("PEo09Dkqv0o", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntGetTrpIconByUri );
 LIB_FUNCTION("kF9zjnlAzIA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntNetSyncTitle );
 LIB_FUNCTION("UXiyfabxFNQ", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyIntNetSyncTitles );
 LIB_FUNCTION("hvdThnVvwdY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyNumInfoGetTotal );
 LIB_FUNCTION("TJCAxto9SEU", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyRegisterContext );
 LIB_FUNCTION("ITUmvpBPaG0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySetInfoGetTrophyFlagArray );
 LIB_FUNCTION("BSoSgiMVHnY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySetInfoGetTrophyNum );
 LIB_FUNCTION("d9jpdPz5f-8", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyShowTrophyList );
 LIB_FUNCTION("JzJdh-JLtu0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemAbortHandle );
 LIB_FUNCTION("z8RCP536GOM", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemBuildGroupIconUri );
 LIB_FUNCTION("Rd2FBOQE094", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemBuildNetTrophyIconUri );
 LIB_FUNCTION("Q182x0rT75I", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemBuildTitleIconUri );
 LIB_FUNCTION("lGnm5Kg-zpA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemBuildTrophyIconUri );
 LIB_FUNCTION("20wAMbXP-u0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemCheckNetSyncTitles );
 LIB_FUNCTION("sKGFFY59ksY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemCheckRecoveryRequired );
 LIB_FUNCTION("JMSapEtDH9Q", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemCloseStorage );
 LIB_FUNCTION("dk27olS4CEE", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemCreateContext );
 LIB_FUNCTION("cBzXEdzVzvs", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemCreateHandle );
 LIB_FUNCTION("8aLlLHKP+No", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDbgCtl );
 LIB_FUNCTION("NobVwD8qcQY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDebugLockTrophy );
 LIB_FUNCTION("yXJlgXljItk", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDebugUnlockTrophy );
 LIB_FUNCTION("U0TOSinfuvw", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDestroyContext );
 LIB_FUNCTION("-LC9hudmD+Y", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDestroyHandle );
 LIB_FUNCTION("q6eAMucXIEM", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemDestroyTrophyConfig );
 LIB_FUNCTION("WdCUUJLQodM", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetDbgParam );
 LIB_FUNCTION("4QYFwC7tn4U", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetDbgParamInt );
 LIB_FUNCTION("OcllHFFcQkI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetGroupIcon );
 LIB_FUNCTION("tQ3tXfVZreU", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetLocalTrophySummary );
 LIB_FUNCTION("g0dxBNTspC0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetNextTitleFileEntryStatus );
 LIB_FUNCTION("sJSDnJRJHhI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetProgress );
 LIB_FUNCTION("X47s4AamPGg", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTitleFileStatus );
 LIB_FUNCTION("7WPj4KCF3D8", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTitleIcon );
 LIB_FUNCTION("pzL+aAk0tQA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTitleSyncStatus );
 LIB_FUNCTION("Ro4sI9xgYl4", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyConfig );
 LIB_FUNCTION("7+OR1TU5QOA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyData );
 LIB_FUNCTION("aXhvf2OmbiE", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyGroupData );
 LIB_FUNCTION("Rkt0bVyaa4Y", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyIcon );
 LIB_FUNCTION("nXr5Rho8Bqk", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyTitleData );
 LIB_FUNCTION("eV1rtLr+eys", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetTrophyTitleIds );
 LIB_FUNCTION("SsGLKTfWfm0", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetUserFileInfo );
 LIB_FUNCTION("XqLLsvl48kA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemGetUserFileStatus );
 LIB_FUNCTION("-qjm2fFE64M", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemIsServerAvailable );
 LIB_FUNCTION("50BvYYzPTsY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemNetSyncTitle );
 LIB_FUNCTION("yDJ-r-8f4S4", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemNetSyncTitles );
 LIB_FUNCTION("mWtsnHY8JZg", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemOpenStorage );
 LIB_FUNCTION("tAxnXpzDgFw", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemPerformRecovery );
 LIB_FUNCTION("tV18n8OcheI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemRemoveAll );
 LIB_FUNCTION("kV4DP0OTMNo", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemRemoveTitleData );
 LIB_FUNCTION("lZSZoN8BstI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemRemoveUserData );
 LIB_FUNCTION("nytN-3-pdvI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemSetDbgParam );
 LIB_FUNCTION("JsRnDKRzvRw", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophySystemSetDbgParamInt );
 LIB_FUNCTION("28xmRUFao68", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , sceNpTrophyUnlockTrophy );
 LIB_FUNCTION("FJZW2oHUHFk", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , Func_149656DA81D41C59 );
 LIB_FUNCTION("n4AHGHb-pfY", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , Func_9F80071876FFA5F6 );
 LIB_FUNCTION("+O9vU1CpGZA", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , Func_F8EF6F5350A91990 );
 LIB_FUNCTION("+not13BEdVI", "libSceNpTrophy" , 1 , "libSceNpTrophy", 1, 1 , Func_FA7A2DD770447552 );
};

}