// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscenpscore.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::NpScore{

int PS4_SYSV_ABI sceNpScoreAbortRequest()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCensorComment()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCensorCommentAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreChangeModeForOtherSaveDataOwners()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCreateNpTitleCtx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCreateNpTitleCtxA()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCreateRequest()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreCreateTitleCtx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreDeleteNpTitleCtx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreDeleteRequest()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetBoardInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetBoardInfoAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRanking()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRankingA()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRankingAAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRankingAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRankingForCrossSave()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetFriendsRankingForCrossSaveAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetGameData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetGameDataAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetGameDataByAccountId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetGameDataByAccountIdAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdForCrossSave()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdForCrossSaveAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdPcId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdPcIdAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdPcIdForCrossSave()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByNpId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByNpIdAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByNpIdPcId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByNpIdPcIdAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRange()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRangeA()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRangeAAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRangeAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRangeForCrossSave()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreGetRankingByRangeForCrossSaveAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScorePollAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreRecordGameData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreRecordGameDataAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreRecordScore()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreRecordScoreAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreSanitizeComment()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreSanitizeCommentAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreSetPlayerCharacterId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreSetThreadParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreSetTimeout()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceNpScoreWaitAsync()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceNpScore(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("1i7kmKbX6hk", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreAbortRequest );
 LIB_FUNCTION("2b3TI0mDYiI", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCensorComment );
 LIB_FUNCTION("4eOvDyN-aZc", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCensorCommentAsync );
 LIB_FUNCTION("dTXC+YcePtM", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreChangeModeForOtherSaveDataOwners );
 LIB_FUNCTION("KnNA1TEgtBI", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCreateNpTitleCtx );
 LIB_FUNCTION("GWnWQNXZH5M", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCreateNpTitleCtxA );
 LIB_FUNCTION("gW8qyjYrUbk", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCreateRequest );
 LIB_FUNCTION("qW9M0bQ-Zx0", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCreateTitleCtx );
 LIB_FUNCTION("G0pE+RNCwfk", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreDeleteNpTitleCtx );
 LIB_FUNCTION("dK8-SgYf6r4", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreDeleteRequest );
 LIB_FUNCTION("LoVMVrijVOk", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetBoardInfo );
 LIB_FUNCTION("Q0Avi9kebsY", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetBoardInfoAsync );
 LIB_FUNCTION("8kuIzUw6utQ", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRanking );
 LIB_FUNCTION("gMbOn+-6eXA", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingA );
 LIB_FUNCTION("6-G9OxL5DKg", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingAAsync );
 LIB_FUNCTION("7SuMUlN7Q6I", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingAsync );
 LIB_FUNCTION("AgcxgceaH8k", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingForCrossSave );
 LIB_FUNCTION("m6F7sE1HQZU", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingForCrossSaveAsync );
 LIB_FUNCTION("zKoVok6FFEI", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameData );
 LIB_FUNCTION("JjOFRVPdQWc", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameDataAsync );
 LIB_FUNCTION("Lmtc9GljeUA", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameDataByAccountId );
 LIB_FUNCTION("PP9jx8s0574", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameDataByAccountIdAsync );
 LIB_FUNCTION("K9tlODTQx3c", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountId );
 LIB_FUNCTION("dRszNNyGWkw", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdAsync );
 LIB_FUNCTION("3Ybj4E1qNtY", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdForCrossSave );
 LIB_FUNCTION("Kc+3QK84AKM", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdForCrossSaveAsync );
 LIB_FUNCTION("wJPWycVGzrs", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdPcId );
 LIB_FUNCTION("bFVjDgxFapc", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdPcIdAsync );
 LIB_FUNCTION("oXjVieH6ZGQ", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdPcIdForCrossSave );
 LIB_FUNCTION("nXaF1Bxb-Nw", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync );
 LIB_FUNCTION("9mZEgoiEq6Y", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpId );
 LIB_FUNCTION("Rd27dqUFZV8", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdAsync );
 LIB_FUNCTION("ETS-uM-vH9Q", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdPcId );
 LIB_FUNCTION("FsouSN0ykN8", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdPcIdAsync );
 LIB_FUNCTION("KBHxDjyk-jA", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRange );
 LIB_FUNCTION("MA9vSt7JImY", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeA );
 LIB_FUNCTION("y5ja7WI05rs", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeAAsync );
 LIB_FUNCTION("rShmqXHwoQE", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeAsync );
 LIB_FUNCTION("nRoYV2yeUuw", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeForCrossSave );
 LIB_FUNCTION("AZ4eAlGDy-Q", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeForCrossSaveAsync );
 LIB_FUNCTION("m1DfNRstkSQ", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScorePollAsync );
 LIB_FUNCTION("bcoVwcBjQ9E", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreRecordGameData );
 LIB_FUNCTION("1gL5PwYzrrw", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreRecordGameDataAsync );
 LIB_FUNCTION("zT0XBtgtOSI", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreRecordScore );
 LIB_FUNCTION("ANJssPz3mY0", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreRecordScoreAsync );
 LIB_FUNCTION("r4oAo9in0TA", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreSanitizeComment );
 LIB_FUNCTION("3UVqGJeDf30", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreSanitizeCommentAsync );
 LIB_FUNCTION("bygbKdHmjn4", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreSetPlayerCharacterId );
 LIB_FUNCTION("yxK68584JAU", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreSetThreadParam );
 LIB_FUNCTION("S3xZj35v8Z8", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreSetTimeout );
 LIB_FUNCTION("fqk8SC63p1U", "libSceNpScore" , 1 , "libSceNpScore", 1, 1 , sceNpScoreWaitAsync );
 LIB_FUNCTION("KnNA1TEgtBI", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreCreateNpTitleCtx );
 LIB_FUNCTION("8kuIzUw6utQ", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRanking );
 LIB_FUNCTION("7SuMUlN7Q6I", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetFriendsRankingAsync );
 LIB_FUNCTION("zKoVok6FFEI", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameData );
 LIB_FUNCTION("JjOFRVPdQWc", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetGameDataAsync );
 LIB_FUNCTION("9mZEgoiEq6Y", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpId );
 LIB_FUNCTION("Rd27dqUFZV8", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdAsync );
 LIB_FUNCTION("ETS-uM-vH9Q", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdPcId );
 LIB_FUNCTION("FsouSN0ykN8", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByNpIdPcIdAsync );
 LIB_FUNCTION("KBHxDjyk-jA", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRange );
 LIB_FUNCTION("rShmqXHwoQE", "libSceNpScoreCompat" , 1 , "libSceNpScore", 1, 1 , sceNpScoreGetRankingByRangeAsync );
};

}