// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscesavedata.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::SaveData{

int PS4_SYSV_ABI sceSaveDataAbort()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataBackup()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataBindPsnAccount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataBindPsnAccountForSystemBackup()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataChangeDatabase()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataChangeInternal()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckBackupData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckBackupDataForCdlg()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckBackupDataInternal()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckCloudData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckIpmiIfSize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckSaveDataBroken()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckSaveDataVersion()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCheckSaveDataVersionLatest()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataClearProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCopy5()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataCreateUploadData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebug()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugCleanMount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugCompiledSdkVersion()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugCreateSaveDataRoot()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugGetThreadId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugRemoveSaveDataRoot()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDebugTarget()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDelete()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDelete5()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDeleteAllUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDeleteCloudData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDeleteUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDirNameSearch()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDirNameSearchInternal()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDownload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetAllSize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetAppLaunchedUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetAutoUploadConditions()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetAutoUploadRequestInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetAutoUploadSetting()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetBoundPsnAccountCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetClientThreadPriority()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetCloudQuotaInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetDataBaseFilePath()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetEventInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetEventResult()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetFormat()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetMountedSaveDataCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetMountInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataMemory2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataRootDir()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataRootPath()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSaveDataRootUsbPath()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetSavePoint()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataGetUpdatedDataCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataInitialize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataInitialize2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataInitialize3()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataInitializeForCdlg()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataIsDeletingUsbDb()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataIsMounted()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataLoadIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataMount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataMount2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataMount5()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataMountInternal()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataMountSys()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataPromote5()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataRebuildDatabase()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataRegisterEventCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataRestoreBackupData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataRestoreBackupDataForCdlg()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataRestoreLoadSaveDataMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSaveIcon()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetAutoUploadSetting()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetEventInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetSaveDataLibraryUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetSaveDataMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetSaveDataMemory2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetupSaveDataMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSetupSaveDataMemory2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataShutdownStart()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSupportedFakeBrokenStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSyncCloudList()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataSyncSaveDataMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataTerminate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataTransferringMount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataUmount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataUmountSys()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataUmountWithBackup()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataUnregisterEventCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataUpload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_02E4C4D201716422()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceSaveData(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("dQ2GohUHXzk", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataAbort );
 LIB_FUNCTION("z1JA8-iJt3k", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataBackup );
 LIB_FUNCTION("kLJQ3XioYiU", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataBindPsnAccount );
 LIB_FUNCTION("hHHCPRqA3+g", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataBindPsnAccountForSystemBackup );
 LIB_FUNCTION("ykwIZfVD08s", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataChangeDatabase );
 LIB_FUNCTION("G0hFeOdRCUs", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataChangeInternal );
 LIB_FUNCTION("RQOqDbk3bSU", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckBackupData );
 LIB_FUNCTION("rYvLW1z2poM", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckBackupDataForCdlg );
 LIB_FUNCTION("v1TrX+3ZB10", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckBackupDataInternal );
 LIB_FUNCTION("-eczr5e4dsI", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckCloudData );
 LIB_FUNCTION("4OPOZxfVkHA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckIpmiIfSize );
 LIB_FUNCTION("1i0rfc+mfa8", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckSaveDataBroken );
 LIB_FUNCTION("p6A1adyQi3E", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckSaveDataVersion );
 LIB_FUNCTION("S49B+I96kpk", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCheckSaveDataVersionLatest );
 LIB_FUNCTION("Wz-4JZfeO9g", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataClearProgress );
 LIB_FUNCTION("YbCO38BOOl4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCopy5 );
 LIB_FUNCTION("kbIIP9aXK9A", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataCreateUploadData );
 LIB_FUNCTION("gW6G4HxBBXA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebug );
 LIB_FUNCTION("bYCnxLexU7M", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugCleanMount );
 LIB_FUNCTION("hVDqYB8+jkk", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugCompiledSdkVersion );
 LIB_FUNCTION("K9gXXlrVLNI", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugCreateSaveDataRoot );
 LIB_FUNCTION("5yHFvMwZX2o", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugGetThreadId );
 LIB_FUNCTION("UGTldPVEdB4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugRemoveSaveDataRoot );
 LIB_FUNCTION("AYBQmnRplrg", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDebugTarget );
 LIB_FUNCTION("S1GkePI17zQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDelete );
 LIB_FUNCTION("SQWusLoK8Pw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDelete5 );
 LIB_FUNCTION("pJrlpCgR8h4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDeleteAllUser );
 LIB_FUNCTION("fU43mJUgKcM", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDeleteCloudData );
 LIB_FUNCTION("uZqc4JpFdeY", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDeleteUser );
 LIB_FUNCTION("dyIhnXq-0SM", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDirNameSearch );
 LIB_FUNCTION("xJ5NFWC3m+k", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDirNameSearchInternal );
 LIB_FUNCTION("h1nP9EYv3uc", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataDownload );
 LIB_FUNCTION("A1ThglSGUwA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetAllSize );
 LIB_FUNCTION("KuXcrMAQIMQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetAppLaunchedUser );
 LIB_FUNCTION("itZ46iH14Vs", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetAutoUploadConditions );
 LIB_FUNCTION("PL20kjAXZZ4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetAutoUploadRequestInfo );
 LIB_FUNCTION("G12foE0S77E", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetAutoUploadSetting );
 LIB_FUNCTION("PzDtD6eBXIM", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetBoundPsnAccountCount );
 LIB_FUNCTION("tu0SDPl+h88", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetClientThreadPriority );
 LIB_FUNCTION("6lZYZqQPfkY", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetCloudQuotaInfo );
 LIB_FUNCTION("CWlBd2Ay1M4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetDataBaseFilePath );
 LIB_FUNCTION("eBSSNIG6hMk", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetEventInfo );
 LIB_FUNCTION("j8xKtiFj0SY", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetEventResult );
 LIB_FUNCTION("UMpxor4AlKQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetFormat );
 LIB_FUNCTION("pc4guaUPVqA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetMountedSaveDataCount );
 LIB_FUNCTION("65VH0Qaaz6s", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetMountInfo );
 LIB_FUNCTION("XgvSuIdnMlw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetParam );
 LIB_FUNCTION("ANmSWUiyyGQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetProgress );
 LIB_FUNCTION("SN7rTPHS+Cg", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataCount );
 LIB_FUNCTION("7Bt5pBC-Aco", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataMemory );
 LIB_FUNCTION("QwOO7vegnV8", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataMemory2 );
 LIB_FUNCTION("+bRDRotfj0Y", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataRootDir );
 LIB_FUNCTION("3luF0xq0DkQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataRootPath );
 LIB_FUNCTION("DwAvlQGvf1o", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSaveDataRootUsbPath );
 LIB_FUNCTION("kb24-4DLyNo", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetSavePoint );
 LIB_FUNCTION("OYmnApJ9q+U", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataGetUpdatedDataCount );
 LIB_FUNCTION("ZkZhskCPXFw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataInitialize );
 LIB_FUNCTION("l1NmDeDpNGU", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataInitialize2 );
 LIB_FUNCTION("TywrFKCoLGY", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataInitialize3 );
 LIB_FUNCTION("g9uwUI3BlQ8", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataInitializeForCdlg );
 LIB_FUNCTION("voAQW45oKuo", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataIsDeletingUsbDb );
 LIB_FUNCTION("ieP6jP138Qo", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataIsMounted );
 LIB_FUNCTION("cGjO3wM3V28", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataLoadIcon );
 LIB_FUNCTION("32HQAQdwM2o", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataMount );
 LIB_FUNCTION("0z45PIH+SNI", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataMount2 );
 LIB_FUNCTION("xz0YMi6BfNk", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataMount5 );
 LIB_FUNCTION("msCER7Iibm8", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataMountInternal );
 LIB_FUNCTION("-XYmdxjOqyA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataMountSys );
 LIB_FUNCTION("uNu7j3pL2mQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataPromote5 );
 LIB_FUNCTION("SgIY-XYA2Xg", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataRebuildDatabase );
 LIB_FUNCTION("hsKd5c21sQc", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataRegisterEventCallback );
 LIB_FUNCTION("lU9YRFsgwSU", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataRestoreBackupData );
 LIB_FUNCTION("HuToUt1GQ8w", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataRestoreBackupDataForCdlg );
 LIB_FUNCTION("aoZKKNjlq3Y", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataRestoreLoadSaveDataMemory );
 LIB_FUNCTION("c88Yy54Mx0w", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSaveIcon );
 LIB_FUNCTION("0VFHv-Fa4w8", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetAutoUploadSetting );
 LIB_FUNCTION("52pL2GKkdjA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetEventInfo );
 LIB_FUNCTION("85zul--eGXs", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetParam );
 LIB_FUNCTION("v3vg2+cooYw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetSaveDataLibraryUser );
 LIB_FUNCTION("h3YURzXGSVQ", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetSaveDataMemory );
 LIB_FUNCTION("cduy9v4YmT4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetSaveDataMemory2 );
 LIB_FUNCTION("v7AAAMo0Lz4", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetupSaveDataMemory );
 LIB_FUNCTION("oQySEUfgXRA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSetupSaveDataMemory2 );
 LIB_FUNCTION("zMgXM79jRhw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataShutdownStart );
 LIB_FUNCTION("+orZm32HB1s", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSupportedFakeBrokenStatus );
 LIB_FUNCTION("LMSQUTxmGVg", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSyncCloudList );
 LIB_FUNCTION("wiT9jeC7xPw", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataSyncSaveDataMemory );
 LIB_FUNCTION("yKDy8S5yLA0", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataTerminate );
 LIB_FUNCTION("WAzWTZm1H+I", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataTransferringMount );
 LIB_FUNCTION("BMR4F-Uek3E", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataUmount );
 LIB_FUNCTION("2-8NWLS8QSA", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataUmountSys );
 LIB_FUNCTION("VwadwBBBJ80", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataUmountWithBackup );
 LIB_FUNCTION("v-AK1AxQhS0", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataUnregisterEventCallback );
 LIB_FUNCTION("COwz3WBj+5s", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , sceSaveDataUpload );
 LIB_FUNCTION("AuTE0gFxZCI", "libSceSaveData" , 1 , "libSceSaveData", 1, 1 , Func_02E4C4D201716422 );
};

}