// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscesavedatadialog.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::SaveDataDialog{

int PS4_SYSV_ABI sceSaveDataDialogClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogGetResult()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogGetStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogInitialize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogIsReadyToDisplay()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogProgressBarInc()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogProgressBarSetValue()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogTerminate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceSaveDataDialogUpdateStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceSaveDataDialog(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("fH46Lag88XY", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogClose );
 LIB_FUNCTION("yEiJ-qqr6Cg", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogGetResult );
 LIB_FUNCTION("ERKzksauAJA", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogGetStatus );
 LIB_FUNCTION("s9e3+YpRnzw", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogInitialize );
 LIB_FUNCTION("en7gNVnh878", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogIsReadyToDisplay );
 LIB_FUNCTION("4tPhsP6FpDI", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogOpen );
 LIB_FUNCTION("V-uEeFKARJU", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogProgressBarInc );
 LIB_FUNCTION("hay1CfTmLyA", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogProgressBarSetValue );
 LIB_FUNCTION("YuH2FA7azqQ", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogTerminate );
 LIB_FUNCTION("KK3Bdg1RWK0", "libSceSaveDataDialog" , 1 , "libSceSaveDataDialog", 1, 1 , sceSaveDataDialogUpdateStatus );
};

}