// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscescreenshot.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::ScreenShot{

int PS4_SYSV_ABI _Z5dummyv()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotCapture()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotDisable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotDisableNotification()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotEnable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotEnableNotification()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotGetAppInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotGetDrcParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotIsDisabled()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotIsVshScreenCaptureDisabled()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotSetOverlayImage()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotSetOverlayImageWithOrigin()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotSetParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceScreenShotSetDrcParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceScreenShot(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("AS45QoYHjc4", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , _Z5dummyv );
 LIB_FUNCTION("JuMLLmmvRgk", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotCapture );
 LIB_FUNCTION("tIYf0W5VTi8", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotDisable );
 LIB_FUNCTION("ysfza71rm9M", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotDisableNotification );
 LIB_FUNCTION("2xxUtuC-RzE", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotEnable );
 LIB_FUNCTION("BDUaqlVdSAY", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotEnableNotification );
 LIB_FUNCTION("hNmK4SdhPT0", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotGetAppInfo );
 LIB_FUNCTION("VlAQIgXa2R0", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotGetDrcParam );
 LIB_FUNCTION("-SV-oTNGFQk", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotIsDisabled );
 LIB_FUNCTION("ICNJ-1POs84", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotIsVshScreenCaptureDisabled );
 LIB_FUNCTION("ahHhOf+QNkQ", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotSetOverlayImage );
 LIB_FUNCTION("73WQ4Jj0nJI", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotSetOverlayImageWithOrigin );
 LIB_FUNCTION("G7KlmIYFIZc", "libSceScreenShot" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotSetParam );
 LIB_FUNCTION("itlWFWV3Tzc", "libSceScreenShotDrc" , 1 , "libSceScreenShot", 0, 9 , sceScreenShotSetDrcParam );
};

}